import java.nio.ByteBuffer;
import java.nio.BufferUnderflowException;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.net.URL;
import java.io.UnsupportedEncodingException;

/**
 * Simple HotBits client.
 *
 * https://www.fourmilab.ch/hotbits/
 * Genuine random numbers, generated by radioactive decay.
 */
class Fourmilab {
  
  String FOURMI_HOTBITS = "https://www.fourmilab.ch/cgi-bin/Hotbits?nbytes=%s&fmt=bin";
  
  String hotbitsURL;
  ByteBuffer buffer;
  
  Fourmilab(int bufferLen) {
    hotbitsURL = String.format(FOURMI_HOTBITS, bufferLen);
    buffer = ByteBuffer.allocate(bufferLen);
    buffer.flip();
  }
    
  protected void readBits() {
    try {
      
      buffer.clear();
      URL url = new URL(hotbitsURL);
      ReadableByteChannel rbc = Channels.newChannel(url.openStream());
      rbc.read(buffer);
      rbc.close();
      buffer.flip();
        
    } catch(IOException e) {
      e.printStackTrace();
      buffer.clear();
    }
  }
  
}

class RandomBits extends Fourmilab {
  public RandomBits(int len) {
    super(len);
  }
  
  int nextBytes() {
    int num = 0;
    try {
        num = buffer.getInt();
    } catch(BufferUnderflowException e) {
        readBits();
        return nextBytes();
    }
    return num;
  }
}

class RandomPassword extends Fourmilab {
  public RandomPassword(int len) {
    super(len);
  }
  
  String genPassword() {    
    byte[] bytes = new byte[buffer.capacity()];
    
    readBits();
    buffer.get(bytes);

    return Base64.encode(bytes);
  }
}

